name: attestation
on: push
permissions: write-all
jobs:
  build-attestation:
    runs-on: ubuntu-Latest
    env:
      aws_region: "us-east-1"
      REGISTRY: public.ecr.aws
    steps:
    - uses: actions/checkout@v4
    - name: auth to aws
      id: auth-aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.aws_region }}
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
    - name: login to ECR
      id: login-ecr
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
    - name: Set up docker
      uses: docker/setup-buildx-action@v3
    - name: build and push
      id: build-push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: public.ecr.aws/x2j7z4y4/docker_test:signed
    - name: Generate artifact attestation
      id: attest-build
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.REGISTRY }}/x2j7z4y4/docker_test
        subject-digest: ${{ steps.build-push.outputs.digest }}
        push-to-registry: true
  pull_request:
    needs: build-attestation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: create pull request
      id: create_pull_request
      run: gh pr create -t "docker_merge" -b "docker merge to master" -B "master"
      with:
        GH_TOKEN: ${{ github.token }}